deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: _site
  on:
    branch: master
language: ruby
rvm:
- 2.2
script: "bundle exec jekyll build && echo "webdesign.albertalvarezcarulla.com" > /_site/CNAME"